### ISSUE TITLE
Names of example scripts are invalid

### ISSUE THREAD

**Issue by peterhinch** [miketeachman/micropython-i2s-examples#3]
Names with embedded `-` characters cause a syntax error on import. I suggest changing them to `_` to avoid confusing beginners.

**Comment by miketeachman** [comment]
Definitely.  Poor choice of filenames.  Thanks for raising the issue.

**Comment by miketeachman** [comment]
Fixed in commit https://github.com/miketeachman/micropython-i2s-examples/commit/bafeb0ea213bcc4868d320b181bd3383f7510a00
