### ISSUE TITLE
Raspberry pi pico - record to sd card: error

### ISSUE THREAD

**Issue by Hubert662** [miketeachman/micropython-i2s-examples#33]
Hello,
First of all, thank you for your post. Great job.
I have a raspberry pi pico and I want to record audio to an SD card. I used your "record_mic_to_sdcard_non_blocking.py" file, and didin't change anything. I copied the "sdcard.py" file to the pico, and again didin't change anything. I have a microphone INMP441 and micro SD card module like this:
![MicroSD-Card-adapter](https://github.com/user-attachments/assets/e565ba2a-7134-41cd-ab07-97b46ec2b96d)

But something is wrong, and this happend:
![screen](https://github.com/user-attachments/assets/789eda05-c47d-4ad7-89de-135dc70d80ce)
Micropython firmware: v1.23.0 (latest)
What could be wrong? What am I doing wrong?
I'm a beginner so maybe I made some simple mistake.

**Comment by miketeachman** [comment]
Sorry for the delay to respond.  Do you still have a problem?
If so, please provide the entire micropython code listing.  It is difficult to help debug the problem with only a few lines of code.  Thanks!

**Comment by Hubert662** [comment]
Thanks for your reply. I solved this problem. I changed "SPI bus speed to SD card" to 20.000.000. Now it works but I have different problem after closing file. I will write about it on the second issue comment.
